import { LitElement } from 'lit';
type SelectOption = {
    key?: string;
    value: string;
} | {
    [key: string]: string;
} | string;
export declare class NxaFormInputTwo extends LitElement {
    static formAssociated: boolean;
    private internals;
    private input?;
    static styles: import("lit").CSSResult;
    label: string;
    placeholder: string;
    value: string;
    name: string;
    type: string;
    size: 'sm' | 'md' | 'lg';
    required: boolean;
    disabled: boolean;
    readonly: boolean;
    floating: boolean;
    checked: boolean;
    min: string;
    max: string;
    step: string;
    inputStyle: 'classic' | 'modern';
    rows: number;
    maxRows: number;
    selectOptions: SelectOption[];
    private touched;
    private valid;
    private invalid;
    private isEmpty;
    constructor();
    private getInputClasses;
    private _handleInput;
    private _adjustHeight;
    private _handleChange;
    private _handleBlur;
    private updateFloatingState;
    validateOnSubmit(): boolean;
    private _validate;
    connectedCallback(): void;
    private _handleFormSubmit;
    firstUpdated(): void;
    private getLabelClasses;
    render(): import("lit-html").TemplateResult<1>;
}
export {};
